version: '3.9'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV : production
      DB_HOST: database
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    depends_on:
    - database
  database:
    image: postgres
    ports:
    - "5432:5432"
