version: '3.9'
services:
  web:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV : development
      DB_HOST: database
    env_file:
      - .env.example
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
  database:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
