version: '3.9'
services:
  web:
    build:
      context: .
      target: test
    environment:
      NODE_ENV : test
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    depends_on:
    - database
    network_mode: host
  database:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: local_test
