version: '3.9'
services:
  web:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV : production
      DB_HOST: database
    env_file:
      - .env
    depends_on:
    - database
  database:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
