version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
      NODE_ENV : production
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    depends_on:
    - postgres
    network_mode: host
  postgres:
    image: postgres
    ports:
    - "5432:5432"
