version: '3.9'
services:
  web:
    build:
      context: .
      target: dev
    environment:
      NODE_ENV : development
      DB_HOST: database
    env_file:
      - .env.example
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    depends_on:
    - database
  database:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
